title: Peixetlift's Projects
description: "A Site For Curious People"
author:
  name: "Peixetlift"
  email: "araventos11@gmail.com"
  url: "https://peixetlift.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Peixetlift"
year : "2021"
